openapi: 3.1.0
info:
  title: YT-DLP Downloader Gateway API
  description: |
    REST API for the Video Download Manager with Optional Dubbing system.

    This API provides job management, control operations, and monitoring for video download and dubbing workflows.
    Real-time updates are available via WebSocket (Socket.IO) at `/api/ws`.
  version: 1.0.0
  contact:
    name: YT-DLP Downloader Project
  license:
    name: MIT

servers:
  - url: http://localhost:3000
    description: Local development server
  - url: https://downloader.example.com
    description: Production server

tags:
  - name: Jobs
    description: Job management operations (create, read, update, delete, control)
  - name: Authentication
    description: User authentication and session management
  - name: Health
    description: Health check and metrics endpoints

paths:
  /api/jobs:
    get:
      summary: List jobs
      description: Retrieve a list of jobs with optional filtering and pagination
      tags:
        - Jobs
      parameters:
        - name: status
          in: query
          description: Filter by job status
          schema:
            type: string
            enum:
              - QUEUED
              - DOWNLOADING
              - DOWNLOADED
              - DUBBING
              - DUBBED
              - MUXING
              - COMPLETE
              - FAILED
              - CANCELED
        - name: search
          in: query
          description: Search by URL or source title
          schema:
            type: string
        - name: limit
          in: query
          description: Maximum number of jobs to return
          schema:
            type: integer
            default: 50
            minimum: 1
            maximum: 200
        - name: offset
          in: query
          description: Number of jobs to skip for pagination
          schema:
            type: integer
            default: 0
            minimum: 0
      responses:
        '200':
          description: List of jobs
          content:
            application/json:
              schema:
                type: object
                properties:
                  jobs:
                    type: array
                    items:
                      $ref: '#/components/schemas/Job'
                  total:
                    type: integer
                    description: Total number of jobs matching filters
                  limit:
                    type: integer
                  offset:
                    type: integer
        '401':
          $ref: '#/components/responses/Unauthorized'

    post:
      summary: Create new job
      description: Submit a new download job with optional dubbing
      tags:
        - Jobs
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - url
              properties:
                url:
                  type: string
                  format: uri
                  description: Video URL from YouTube or yt-dlp-supported service
                  example: https://www.youtube.com/watch?v=dQw4w9WgXcQ
                requestedDubbing:
                  type: boolean
                  description: Enable dubbing workflow
                  default: false
                targetLang:
                  type: string
                  description: Target language for dubbing (ISO 639-1 code)
                  default: ru
                  example: ru
                formatPreset:
                  type: string
                  description: yt-dlp format selection preset
                  default: bestvideo+bestaudio
                  enum:
                    - bestvideo+bestaudio
                    - best
                    - bestaudio
                    - worst
                  example: bestvideo+bestaudio
                outputContainer:
                  type: string
                  description: Output container format
                  default: mkv
                  enum:
                    - mkv
                    - mp4
                    - webm
                  example: mkv
                priority:
                  type: integer
                  description: Job priority (higher = earlier execution)
                  default: 0
                  minimum: 0
                  maximum: 10
      responses:
        '201':
          description: Job created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /api/jobs/{id}:
    get:
      summary: Get job details
      description: Retrieve detailed information for a specific job including media metadata and event history
      tags:
        - Jobs
      parameters:
        - $ref: '#/components/parameters/JobId'
      responses:
        '200':
          description: Job details
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Job'
                  - type: object
                    properties:
                      media:
                        $ref: '#/components/schemas/Media'
                      events:
                        type: array
                        items:
                          $ref: '#/components/schemas/JobEvent'
        '404':
          $ref: '#/components/responses/NotFound'
        '401':
          $ref: '#/components/responses/Unauthorized'

    delete:
      summary: Delete job
      description: Delete a job and associated media files
      tags:
        - Jobs
      parameters:
        - $ref: '#/components/parameters/JobId'
      responses:
        '204':
          description: Job deleted successfully
        '404':
          $ref: '#/components/responses/NotFound'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /api/jobs/{id}/cancel:
    post:
      summary: Cancel job
      description: Cancel an active job
      tags:
        - Jobs
      parameters:
        - $ref: '#/components/parameters/JobId'
      responses:
        '200':
          description: Job canceled successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'
        '404':
          $ref: '#/components/responses/NotFound'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /api/jobs/{id}/retry:
    post:
      summary: Retry job
      description: Retry a failed or canceled job from the beginning
      tags:
        - Jobs
      parameters:
        - $ref: '#/components/parameters/JobId'
      responses:
        '200':
          description: Job restarted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'
        '404':
          $ref: '#/components/responses/NotFound'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /api/jobs/{id}/resume:
    post:
      summary: Resume job
      description: Resume a failed dubbing job from the last successful checkpoint
      tags:
        - Jobs
      parameters:
        - $ref: '#/components/parameters/JobId'
      responses:
        '200':
          description: Job resumed successfully
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Job'
                  - type: object
                    properties:
                      resumedFrom:
                        type: string
                        description: Stage from which job was resumed
                        example: DOWNLOADED
        '404':
          $ref: '#/components/responses/NotFound'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /api/jobs/{id}/logs:
    get:
      summary: Get job logs
      description: Retrieve event logs for a specific job with pagination
      tags:
        - Jobs
      parameters:
        - $ref: '#/components/parameters/JobId'
        - name: limit
          in: query
          description: Maximum number of log entries to return
          schema:
            type: integer
            default: 100
            minimum: 1
            maximum: 1000
        - name: offset
          in: query
          description: Number of log entries to skip for pagination
          schema:
            type: integer
            default: 0
            minimum: 0
      responses:
        '200':
          description: Job event logs
          content:
            application/json:
              schema:
                type: object
                properties:
                  events:
                    type: array
                    items:
                      $ref: '#/components/schemas/JobEvent'
                  total:
                    type: integer
                  limit:
                    type: integer
                  offset:
                    type: integer
        '404':
          $ref: '#/components/responses/NotFound'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /api/auth/login:
    post:
      summary: Login
      description: Authenticate user and obtain session token
      tags:
        - Authentication
      security: []  # No authentication required for login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  example: admin
                password:
                  type: string
                  format: password
                  example: password123
      responses:
        '200':
          description: Authentication successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: JWT session token
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                      username:
                        type: string
                      role:
                        type: string
                        enum:
                          - admin
                          - user
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/auth/logout:
    post:
      summary: Logout
      description: Invalidate session token
      tags:
        - Authentication
      responses:
        '204':
          description: Logout successful
        '401':
          $ref: '#/components/responses/Unauthorized'

  /healthz:
    get:
      summary: Health check
      description: Check health status of Gateway and dependencies (Redis, SQLite)
      tags:
        - Health
      security: []  # Health endpoint is public
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                      - ok
                      - degraded
                      - unhealthy
                    example: ok
                  uptime:
                    type: number
                    description: Service uptime in seconds
                    example: 3600
                  dependencies:
                    type: object
                    properties:
                      redis:
                        type: string
                        enum:
                          - ok
                          - error
                        example: ok
                      sqlite:
                        type: string
                        enum:
                          - ok
                          - error
                        example: ok
                      filesystem:
                        type: string
                        enum:
                          - ok
                          - error
                        example: ok
                  timestamp:
                    type: string
                    format: date-time
        '503':
          description: Service is unhealthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                      - unhealthy
                  error:
                    type: string
                    description: Error message describing health issue

  /metrics:
    get:
      summary: Prometheus metrics
      description: Export Prometheus-compatible metrics
      tags:
        - Health
      security: []  # Metrics endpoint is public
      responses:
        '200':
          description: Prometheus text format metrics
          content:
            text/plain:
              schema:
                type: string
                example: |
                  # HELP jobs_total Total number of jobs created
                  # TYPE jobs_total counter
                  jobs_total 1234

                  # HELP jobs_active Number of active jobs
                  # TYPE jobs_active gauge
                  jobs_active 3

                  # HELP bytes_downloaded_total Total bytes downloaded
                  # TYPE bytes_downloaded_total counter
                  bytes_downloaded_total 1073741824

components:
  schemas:
    Job:
      type: object
      properties:
        id:
          type: string
          description: Job ID (UUIDv7)
          example: 01JQXXX1234567890ABCDEFGH
        url:
          type: string
          format: uri
          description: Source video URL
          example: https://www.youtube.com/watch?v=dQw4w9WgXcQ
        status:
          type: string
          enum:
            - QUEUED
            - DOWNLOADING
            - DOWNLOADED
            - DUBBING
            - DUBBED
            - MUXING
            - COMPLETE
            - FAILED
            - CANCELED
          description: Current job status
          example: DOWNLOADING
        priority:
          type: integer
          description: Job priority
          example: 0
        requestedDubbing:
          type: boolean
          description: Whether dubbing was requested
          example: true
        targetLang:
          type: string
          description: Target language for dubbing
          example: ru
        formatPreset:
          type: string
          description: yt-dlp format preset
          example: bestvideo+bestaudio
        outputContainer:
          type: string
          description: Output container format
          example: mkv
        createdAt:
          type: string
          format: date-time
          description: Job creation timestamp
          example: 2026-01-24T12:00:00Z
        updatedAt:
          type: string
          format: date-time
          description: Last update timestamp
          example: 2026-01-24T12:05:30Z
        retries:
          type: integer
          description: Number of retry attempts
          example: 0
        error:
          type: string
          nullable: true
          description: Error message if job failed
          example: null

    Media:
      type: object
      properties:
        id:
          type: integer
          description: Media record ID
        jobId:
          type: string
          description: Associated job ID
        videoPath:
          type: string
          description: Path to final video file
          example: /media/library/channel/video.mkv
        audioOriginalPath:
          type: string
          nullable: true
          description: Path to extracted original audio (cached)
          example: /media/tmp/01JQXXX/original.wav
        audioDubbedPath:
          type: string
          nullable: true
          description: Path to dubbed audio file
          example: /media/tmp/01JQXXX/dubbed.wav
        tempDir:
          type: string
          nullable: true
          description: Temporary directory for processing
          example: /media/tmp/01JQXXX
        durationSec:
          type: number
          nullable: true
          description: Video duration in seconds
          example: 300.5
        width:
          type: integer
          nullable: true
          description: Video width in pixels
          example: 1920
        height:
          type: integer
          nullable: true
          description: Video height in pixels
          example: 1080
        sourceTitle:
          type: string
          nullable: true
          description: Video title from source
          example: Never Gonna Give You Up
        sourceId:
          type: string
          nullable: true
          description: Video ID from source
          example: dQw4w9WgXcQ
        sourceUploader:
          type: string
          nullable: true
          description: Uploader/channel name
          example: RickAstleyVEVO

    JobEvent:
      type: object
      properties:
        id:
          type: integer
          description: Event ID
        jobId:
          type: string
          description: Associated job ID
        timestamp:
          type: string
          format: date-time
          description: Event timestamp
          example: 2026-01-24T12:01:00Z
        event:
          type: string
          description: Event type
          enum:
            - progress
            - state_change
            - log
            - error
          example: progress
        payload:
          type: object
          description: Event-specific data
          example:
            stage: downloading
            percent: 45.2
            speed: 1024000
            eta: 15

    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message
          example: Invalid request parameters
        code:
          type: string
          description: Error code
          example: VALIDATION_ERROR
        details:
          type: object
          description: Additional error details
          nullable: true

  parameters:
    JobId:
      name: id
      in: path
      required: true
      description: Job ID (UUIDv7)
      schema:
        type: string
        example: 01JQXXX1234567890ABCDEFGH

  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error: Unauthorized
            code: UNAUTHORIZED

    NotFound:
      description: Not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error: Job not found
            code: NOT_FOUND

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token obtained from /api/auth/login

security:
  - BearerAuth: []
